#cloud-config

repo_update: true
repo_upgrade: all

write_files:
  - path: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
    content: |
      [Service]
      Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
  - path: /etc/systemd/system/docker.service.d/00-cgroup-systemd.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd
  - path: /etc/sysctl.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.ipv6.conf.default.forwarding = 1
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

packages:
  - unattended-upgrades
  - docker-ce
  - kubeadm
  - kubectl
  - kubelet

apt:
  sources:
    docker.list:
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
    kube.list:
      keyid: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
      source: "deb http://packages.cloud.google.com/apt/ kubernetes-xenial main"

runcmd:
  - "systemctl daemon-reload"
  - "sysctl -p"
